services:
  - type: web
    name: LaravelApp
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: local
      - key: APP_KEY
        value: base64:hf21r9Ai4cofGVcREZ7PiOPtlqmUYHWhJgVWsj2e2ts=
      - key: APP_DEBUG
        value: true
      - key: APP_TIMEZONE
        value: UTC
      - key: APP_URL
        value: http://localhost
      - key: APP_LOCALE
        value: en
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: APP_FAKER_LOCALE
        value: en_US
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: test_project
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: 
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: sandbox.smtp.mailtrap.io
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: 2e71790ea61cfa
      - key: MAIL_PASSWORD
        value: 91e6fcb1411292
      - key: MAIL_FROM_ADDRESS
        value: hello@example.com
      - key: MAIL_FROM_NAME
        value: Laravel
      - key: REDIS_CLIENT
        value: phpredis
      - key: REDIS_HOST
        value: 127.0.0.1
      - key: REDIS_PORT
        value: 6379
      - key: VITE_APP_NAME
        value: Laravel
